# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zH5_npwKiuWiVer9wzycdKgPuOguXvQD
"""

!pip install timm opencv-python scikit-learn

import os, cv2, torch, timm, random
import numpy as np
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

from google.colab import files
uploaded= files.upload()

import os

zip_path = "/content/processed_dataset.zip"
print("File exists:", os.path.exists(zip_path))

import zipfile

extract_path = "/content/processed_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted to:", extract_path)

for root, dirs, files in os.walk(extract_path):
    level = root.replace(extract_path, "").count(os.sep)
    indent = " " * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    for f in files[:3]:
        print(f"{indent}  {f}")

from collections import defaultdict

counts = defaultdict(int)

for modality in ["rgb", "grayscale", "contrast"]:
    for split in ["train", "val", "test"]:
        path = os.path.join(extract_path, modality, split)
        if os.path.exists(path):
            counts[(modality, split)] = len(os.listdir(path))

for (modality, split), count in counts.items():
    print(f"{modality.upper()} | {split.upper()} : {count}")

import os

VALID_EXT = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

def get_image_files(folder):
    return [
        f for f in os.listdir(folder)
        if f.lower().endswith(VALID_EXT)
    ]

import cv2

def inspect_image(path):
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if img is None:
        raise ValueError(f"Could not read image: {path}")
    return img.shape

import os

for modality in ["rgb", "grayscale", "contrast"]:
    path = os.path.join(extract_path, modality, "train")
    print(f"\n📁 {path}")
    print(os.listdir(path))

VALID_EXT = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

def get_all_images(root_dir):
    image_paths = []
    for root, _, files in os.walk(root_dir):
        for f in files:
            if f.lower().endswith(VALID_EXT):
                image_paths.append(os.path.join(root, f))
    return image_paths

for modality in ["rgb", "grayscale", "contrast"]:
    for split in ["train", "val", "test"]:
        path = os.path.join(extract_path, modality, split, "ship")
        imgs = get_all_images(path)
        print(f"{modality.upper()} | {split.upper()} | SHIP: {len(imgs)}")

import os, cv2, torch, timm, random
import numpy as np
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

VALID_EXT = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

def get_all_images(root):
    imgs = []
    for r, _, files in os.walk(root):
        for f in files:
            if f.lower().endswith(VALID_EXT):
                imgs.append(os.path.join(r, f))
    return imgs

def make_no_ship(img):
    img = cv2.GaussianBlur(img, (51,51), 0)
    noise = np.random.normal(0, 20, img.shape).astype(np.uint8)
    img = cv2.add(img, noise)
    return img

class UnifiedShipDataset(Dataset):
    def __init__(self, root, split):
        self.ship_images = []

        for modality in ["rgb", "grayscale", "contrast"]:
            ship_dir = os.path.join(root, modality, split, "ship")
            self.ship_images += get_all_images(ship_dir)

        self.transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485,0.456,0.406],
                std=[0.229,0.224,0.225]
            )
        ])

    def __len__(self):
        return len(self.ship_images) * 2  # ship + synthetic no-ship

    def __getitem__(self, idx):
        img_path = self.ship_images[idx // 2]
        img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)

        if img.ndim == 2:
            img = np.stack([img]*3, axis=-1)

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        label = 1  # ship

        if idx % 2 == 1:
            img = make_no_ship(img)
            label = 0  # no-ship

        img = self.transform(img)
        return img, label

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 12
CONF_THRESHOLD = 0.65
DATA_ROOT = "/content/processed_dataset"

train_ds = UnifiedShipDataset(DATA_ROOT, "train")
val_ds   = UnifiedShipDataset(DATA_ROOT, "val")
test_ds  = UnifiedShipDataset(DATA_ROOT, "test")

train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
test_dl  = DataLoader(test_ds, batch_size=BATCH_SIZE)

def visualize_augmentation(dataset, n=3):
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(n, 3, figsize=(9, 3*n))

    for i in range(n):
        img, label = dataset[random.randint(0, len(dataset)-1)]
        img = img.permute(1,2,0).cpu().numpy()
        img = (img - img.min()) / (img.max() - img.min())

        axes[i,0].imshow(img)
        axes[i,0].set_title(f"Augmented | Label={label}")
        axes[i,0].axis("off")

    plt.show()

visualize_augmentation(train_ds)

def get_model(backbone="efficientnet_b0"):
    model = timm.create_model(backbone, pretrained=True, num_classes=0)
    feat_dim = model.num_features

    classifier = nn.Linear(feat_dim, 2)
    return model, classifier, feat_dim

class ShipNet(nn.Module):
    def __init__(self, backbone_name):
        super().__init__()
        self.backbone, self.classifier, self.feat_dim = get_model(backbone_name)

    def forward(self, x):
        feat = self.backbone(x)
        out = self.classifier(feat)
        return out, feat

from torchvision import transforms

train_transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.RandomHorizontalFlip(0.5),
    transforms.RandomVerticalFlip(0.5),
    transforms.RandomRotation(20),
    transforms.ColorJitter(
        brightness=0.3,
        contrast=0.3,
        saturation=0.2,
        hue=0.05
    ),
    transforms.RandomAffine(
        degrees=0,
        translate=(0.1, 0.1),
        scale=(0.9, 1.1)
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

class UnifiedShipDataset(Dataset):
    def __init__(self, root, split):
        self.ship_images = []
        self.split = split

        for modality in ["rgb", "grayscale", "contrast"]:
            ship_dir = os.path.join(root, modality, split, "ship")
            self.ship_images += get_all_images(ship_dir)

        self.transform = train_transform if split == "train" else eval_transform

    def __len__(self):
        return len(self.ship_images) * 2  # ship + synthetic no-ship

    def __getitem__(self, idx):
        img_path = self.ship_images[idx // 2]
        img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)

        if img.ndim == 2:
            img = np.stack([img]*3, axis=-1)

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (224, 224))

        label = 1  # ship

        if idx % 2 == 1:
            img = make_no_ship(img)
            label = 0

        img = self.transform(img)
        return img, label

class ShipNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = timm.create_model(
            "efficientnet_b0",
            pretrained=True,
            num_classes=0
        )
        self.classifier = nn.Linear(1280, 2)

    def forward(self, x):
        feat = self.backbone(x)
        out = self.classifier(feat)
        return out, feat

model = ShipNet().to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)

def make_no_ship(img):
    img = cv2.GaussianBlur(img, (51,51), 0)
    noise = np.random.normal(0, 20, img.shape).astype(np.uint8)
    img = cv2.add(img, noise)
    return img

def __getitem__(self, idx):
    img_path = self.ship_images[idx // 2]
    img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)

    # Convert grayscale / contrast to 3-channel
    if img.ndim == 2:
        img = np.stack([img]*3, axis=-1)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (224, 224))

    label = 1  # Ship

    if idx % 2 == 1:
        img = make_no_ship(img)   # 👈 YOUR FUNCTION
        label = 0                 # No-Ship

def __getitem__(self, idx):
    img_path = self.ship_images[idx // 2]
    img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)

    # Convert grayscale / contrast to 3-channel
    if img.ndim == 2:
        img = np.stack([img]*3, axis=-1)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (224, 224))

    label = 1  # Ship

    # 🔹 Synthetic No-Ship generation
    if idx % 2 == 1:
        img = make_no_ship(img)
        label = 0  # No-Ship

    # 🔹 Apply augmentation / normalization
    img = self.transform(img)

    return img, label

from torchvision import transforms

eval_transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

train_ds = UnifiedShipDataset(DATA_ROOT, split="train")
val_ds   = UnifiedShipDataset(DATA_ROOT, split="val")
test_ds  = UnifiedShipDataset(DATA_ROOT, split="test")

import torch
import torch.nn as nn
import timm

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

class ShipNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = timm.create_model(
            "efficientnet_b0",
            pretrained=True,
            num_classes=0   # remove ImageNet head
        )
        self.classifier = nn.Linear(1280, 2)  # Ship / No-Ship

    def forward(self, x):
        features = self.backbone(x)
        logits = self.classifier(features)
        return logits, features

model = ShipNet().to(DEVICE)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)

for p in model.backbone.parameters():
    p.requires_grad = False

optimizer = torch.optim.AdamW(model.classifier.parameters(), lr=1e-3)

EPOCHS = 10
for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0

    for x, y in train_dl:
        x, y = x.to(DEVICE), y.to(DEVICE)

        optimizer.zero_grad()
        logits, _ = model(x)
        loss = criterion(logits, y)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    train_loss /= len(train_dl)

    print(f"Epoch [{epoch+1}/{EPOCHS}] | Train Loss: {train_loss:.4f}")

import torch
import numpy as np

@torch.no_grad()
def compute_ship_centroid_fast(model, loader):
    model.eval()

    feat_sum = None
    count = 0

    for x, y in loader:
        # Move only once
        x = x.to(DEVICE)
        y = y.to(DEVICE)

        # Forward pass
        _, feats = model(x)

        # Select only ship features
        ship_feats = feats[y == 1]

        if ship_feats.numel() == 0:
            continue

        if feat_sum is None:
            feat_sum = ship_feats.sum(dim=0)
        else:
            feat_sum += ship_feats.sum(dim=0)

        count += ship_feats.size(0)

    # Final centroid
    centroid = (feat_sum / count).cpu().numpy()
    return centroid

test_dl_fast = DataLoader(
    test_ds,
    batch_size=64,          # increase if GPU allows (128 is even better)
    shuffle=False,
    num_workers=4,          # Colab: 2–4 is optimal
    pin_memory=True
)

import torch
import numpy as np

@torch.no_grad()
def extract_features_fast(model, loader, device):
    model.eval()

    # Get feature dimension
    sample_batch = next(iter(loader))[0].to(device)
    _, sample_feat = model(sample_batch)
    feat_dim = sample_feat.shape[1]

    total_samples = len(loader.dataset)
    features = torch.empty((total_samples, feat_dim), dtype=torch.float32)

    idx = 0
    for x, _ in loader:
        bsz = x.size(0)
        x = x.to(device, non_blocking=True)

        _, f = model(x)
        features[idx:idx+bsz] = f.cpu()
        idx += bsz

    return features.numpy()

features = extract_features_fast(model, test_dl_fast, DEVICE)

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(
    eps=8.0,          # tune between 6–10
    min_samples=10,
    metric="euclidean",
    n_jobs=-1
)

cluster_labels = dbscan.fit_predict(features)

import numpy as np

unique, counts = np.unique(cluster_labels, return_counts=True)

print("Cluster distribution:")
for u, c in zip(unique, counts):
    if u == -1:
        print(f"Unknown / Outliers: {c}")
    else:
        print(f"Cluster {u}: {c}")

!pip install umap-learn

import umap
import matplotlib.pyplot as plt

reducer = umap.UMAP(
    n_neighbors=15,
    min_dist=0.1,
    n_components=2,
    random_state=42
)

features_2d = reducer.fit_transform(features)

plt.figure(figsize=(7,6))
plt.scatter(
    features_2d[:,0],
    features_2d[:,1],
    c=cluster_labels,
    cmap="tab10",
    s=5
)
plt.title("Ship Clustering (EfficientNet-B0 Features)")
plt.colorbar()
plt.show()

from sklearn.neighbors import NearestNeighbors

nn_index = NearestNeighbors(n_neighbors=1, metric="euclidean")
nn_index.fit(features)

def assign_cluster(new_feature):
    dist, idx = nn_index.kneighbors(new_feature.reshape(1, -1))
    return cluster_labels[idx[0][0]], dist[0][0]

def cluster_based_unknown(new_feature, dist_thresh=15.0):
    cluster_id, dist = assign_cluster(new_feature)

    if cluster_id == -1 or dist > dist_thresh:
        return "Unknown Ship", cluster_id, dist

    return "Known Ship", cluster_id, dist

import joblib

joblib.dump(dbscan, "dbscan_model.pkl")
joblib.dump(nn_index, "nn_index.pkl")
np.save("ship_features.npy", features)
np.save("ship_cluster_labels.npy", cluster_labels)

torch.save({
    "model_state": model.state_dict()
}, "efficientnet_b0_ship.pth")

def load_full_system(device="cuda"):
    # Model
    model = ShipNet().to(device)
    checkpoint = torch.load("efficientnet_b0_ship.pth", map_location=device)
    model.load_state_dict(checkpoint["model_state"])
    model.eval()

    # Other objects
    dbscan = joblib.load("dbscan_model.pkl")
    nn_index = joblib.load("nn_index.pkl")
    ship_centroid = np.load("ship_centroid.npy")

    return model, dbscan, nn_index, ship_centroid

class GradCAM:
    def __init__(self, model):
        self.model = model
        self.grad = None
        self.act = None

        layer = model.backbone.conv_head
        layer.register_forward_hook(self._save_act)
        layer.register_backward_hook(self._save_grad)

    def _save_act(self, m, i, o): self.act = o
    def _save_grad(self, m, gi, go): self.grad = go[0]

    def generate(self, x, cls):
        self.model.zero_grad()
        logits,_ = self.model(x)
        logits[0,cls].backward()

        w = self.grad.mean(dim=(2,3), keepdim=True)
        cam = (w * self.act).sum(1)
        cam = torch.relu(cam)
        cam = cam.squeeze().detach().cpu().numpy()
        return cam / cam.max()

import matplotlib.pyplot as plt
import cv2
from torchvision import transforms

def run_full_pipeline(image_path):
    device = DEVICE

    model, dbscan, nn_index, ship_centroid = load_full_system(device)
    gradcam = GradCAM(model)

    # --- Preprocess ---
    img_raw = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    if img_raw.ndim == 2:
        img_raw = np.stack([img_raw]*3, axis=-1)

    img_rgb = cv2.cvtColor(img_raw, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, (224,224))

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485,0.456,0.406],
            std=[0.229,0.224,0.225]
        )
    ])

    x = transform(img_resized).unsqueeze(0).to(device)

    # --- Prediction ---
    with torch.no_grad():
        logits, feat = model(x)
        probs = torch.softmax(logits,1)
        conf, pred = probs.max(1)

    confidence = conf.item()
    label = "Ship" if pred.item()==1 else "No-Ship"

    # --- Unknown detection ---
    dist = np.linalg.norm(feat.cpu().numpy() - ship_centroid)
    if confidence < 0.65 or dist > 15:
        final_label = "Unknown Ship"
    else:
        final_label = label

    # --- Clustering ---
    _, idx = nn_index.kneighbors(feat.cpu().numpy())
    cluster_id = int(cluster_labels[idx[0][0]])

    # --- Grad-CAM ---
    cam = gradcam.generate(x, pred.item())

    # --- Display ---
    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(img_rgb)
    plt.title("Input Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(cam, cmap="jet")
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.text(0.1,0.8,f"Label: {final_label}", fontsize=12)
    plt.text(0.1,0.6,f"Confidence: {confidence:.3f}", fontsize=12)
    plt.text(0.1,0.4,f"Cluster ID: {cluster_id}", fontsize=12)
    plt.text(0.1,0.2,f"Distance: {dist:.2f}", fontsize=12)
    plt.axis("off")

    plt.show()

from google.colab import files
uploaded= files.upload()

ship_centroid = compute_ship_centroid_fast(model, train_dl)

np.save("ship_centroid.npy", ship_centroid)

import os
print("Exists:", os.path.exists("ship_centroid.npy"))
print("Shape:", ship_centroid.shape)
print("Dtype:", ship_centroid.dtype)

import torch

torch.save(model.state_dict(), "efficientnet_b0_ship.pth")

import torch

torch.save(model.state_dict(), "efficientnet_b0_ship.pth")

import joblib
import numpy as np

joblib.dump(dbscan, "dbscan.pkl")
joblib.dump(nn_index, "nn_index.pkl")

np.save("ship_centroid.npy", ship_centroid.astype(np.float32))
np.save("cluster_labels.npy", cluster_labels)

import timm
import torch.nn as nn

class ShipNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = timm.create_model(
            "efficientnet_b0",
            pretrained=False,
            num_classes=0
        )
        self.classifier = nn.Linear(1280, 2)

    def forward(self, x):
        feat = self.backbone(x)
        out = self.classifier(feat)
        return out, feat

def load_entire_system(device="cuda"):
    model = ShipNet().to(device)
    model.load_state_dict(torch.load("efficientnet_b0_ship.pth", map_location=device))
    model.eval()

    dbscan = joblib.load("dbscan.pkl")
    nn_index = joblib.load("nn_index.pkl")
    ship_centroid = np.load("ship_centroid.npy")
    cluster_labels = np.load("cluster_labels.npy")

    return model, dbscan, nn_index, ship_centroid, cluster_labels

class GradCAM:
    def __init__(self, model):
        self.model = model
        self.grad = None
        self.act = None

        layer = model.backbone.conv_head
        layer.register_forward_hook(self.save_act)
        layer.register_backward_hook(self.save_grad)

    def save_act(self, m, i, o): self.act = o
    def save_grad(self, m, gi, go): self.grad = go[0]

    def generate(self, x, cls):
        self.model.zero_grad()
        logits,_ = self.model(x)
        logits[0,cls].backward()

        w = self.grad.mean(dim=(2,3), keepdim=True)
        cam = (w * self.act).sum(1)
        cam = torch.relu(cam)
        cam = cam.squeeze().detach().cpu().numpy()
        return cam / cam.max()

import cv2
import matplotlib.pyplot as plt
from torchvision import transforms

def run_inference(image_path,
                  conf_thresh=0.65,
                  dist_thresh=15.0):

    device = "cuda" if torch.cuda.is_available() else "cpu"

    model, dbscan, nn_index, ship_centroid, cluster_labels = load_entire_system(device)
    gradcam = GradCAM(model)

    # --- Preprocess image ---
    img_raw = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    if img_raw.ndim == 2:
        img_raw = np.stack([img_raw]*3, axis=-1)

    img_rgb = cv2.cvtColor(img_raw, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, (224,224))

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485,0.456,0.406],
            std=[0.229,0.224,0.225]
        )
    ])

    x = transform(img_resized).unsqueeze(0).to(device)

    # --- Model inference ---
    with torch.no_grad():
        logits, feat = model(x)
        probs = torch.softmax(logits,1)
        conf, pred = probs.max(1)

    confidence = conf.item()
    raw_label = "Ship" if pred.item()==1 else "No-Ship"

    # --- Unknown detection ---
    dist = np.linalg.norm(feat.detach().cpu().numpy() - ship_centroid)
    final_label = raw_label

    if confidence < conf_thresh or dist > dist_thresh:
        final_label = "Unknown Ship"

    # --- Clustering ---
    _, idx = nn_index.kneighbors(feat.detach().cpu().numpy())
    cluster_id = int(cluster_labels[idx[0][0]])

    # --- Grad-CAM ---
    cam = gradcam.generate(x, pred.item())

    # --- Display ---
    plt.figure(figsize=(14,4))

    plt.subplot(1,3,1)
    plt.imshow(img_rgb)
    plt.title("Input Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(cam, cmap="jet")
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.text(0.05,0.8,f"Final Label: {final_label}", fontsize=12)
    plt.text(0.05,0.6,f"Confidence: {confidence:.3f}", fontsize=12)
    plt.text(0.05,0.4,f"Cluster ID: {cluster_id}", fontsize=12)
    plt.text(0.05,0.2,f"Distance: {dist:.2f}", fontsize=12)
    plt.axis("off")

    plt.show()

run_inference("/content/test.jpg")



import os

files = [
    "efficientnet_b0_ship.pth",
    "dbscan.pkl",
    "nn_index.pkl",
    "ship_centroid.npy",
    "cluster_labels.npy"
]

for f in files:
    print(f, "→", os.path.exists(f))

from google.colab import files

files.download("efficientnet_b0_ship.pth")
files.download("dbscan.pkl")
files.download("nn_index.pkl")
files.download("ship_centroid.npy")
files.download("cluster_labels.npy")

import zipfile

with zipfile.ZipFile("ship_detection_system.zip", "w") as z:
    z.write("efficientnet_b0_ship.pth")
    z.write("dbscan.pkl")
    z.write("nn_index.pkl")
    z.write("ship_centroid.npy")
    z.write("cluster_labels.npy")

from google.colab import files
files.download("ship_detection_system.zip")

from google.colab import files
uploaded= files.upload();

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)

def load_entire_system(device=DEVICE):
    model = ShipNet().to(device)
    model.load_state_dict(torch.load("efficientnet_b0_ship.pth", map_location=device))
    model.eval()

    dbscan = joblib.load("dbscan.pkl")
    nn_index = joblib.load("nn_index.pkl")
    ship_centroid = np.load("ship_centroid.npy")
    cluster_labels = np.load("cluster_labels.npy")

    return model, dbscan, nn_index, ship_centroid, cluster_labels

import cv2
import matplotlib.pyplot as plt
from torchvision import transforms

def run_inference(image_path,
                  conf_thresh=0.65,
                  dist_thresh=15.0):

    device = DEVICE

    model, dbscan, nn_index, ship_centroid, cluster_labels = load_entire_system(device)
    gradcam = GradCAM(model)

    # --- Preprocess image ---
    img_raw = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    if img_raw.ndim == 2:
        img_raw = np.stack([img_raw]*3, axis=-1)

    img_rgb = cv2.cvtColor(img_raw, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, (224,224))

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485,0.456,0.406],
            std=[0.229,0.224,0.225]
        )
    ])

    x = transform(img_resized).unsqueeze(0).to(device)

    # --- Model inference ---
    with torch.no_grad():
        logits, feat = model(x)
        probs = torch.softmax(logits,1)
        conf, pred = probs.max(1)

    confidence = conf.item()
    raw_label = "Ship" if pred.item()==1 else "No-Ship"

    # --- Unknown detection ---
    dist = np.linalg.norm(feat.detach().cpu().numpy() - ship_centroid)
    final_label = raw_label

    if confidence < conf_thresh or dist > dist_thresh:
        final_label = "Unknown Ship"

    # --- Clustering ---
    _, idx = nn_index.kneighbors(feat.detach().cpu().numpy())
    cluster_id = int(cluster_labels[idx[0][0]])

    # --- Grad-CAM ---
    cam = gradcam.generate(x, pred.item())

    # --- Display ---
    plt.figure(figsize=(14,4))

    plt.subplot(1,3,1)
    plt.imshow(img_rgb)
    plt.title("Input Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(cam, cmap="jet")
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.text(0.05,0.8,f"Final Label: {final_label}", fontsize=12)
    plt.text(0.05,0.6,f"Confidence: {confidence:.3f}", fontsize=12)
    plt.text(0.05,0.4,f"Cluster ID: {cluster_id}", fontsize=12)
    plt.text(0.05,0.2,f"Distance: {dist:.2f}", fontsize=12)
    plt.axis("off")

    plt.show()

model, dbscan, nn_index, ship_centroid, cluster_labels = load_entire_system()
run_inference("test1.jpg")

import torch

def compute_accuracy(model, dataloader):
    correct = 0
    total = 0

    model.eval()
    with torch.no_grad():
        for x, y in dataloader:
            x = x.to(DEVICE)
            y = y.to(DEVICE)

            logits, _ = model(x)
            preds = logits.argmax(dim=1)

            correct += (preds == y).sum().item()
            total += y.size(0)

    return correct / total

test_accuracy = compute_accuracy(model, test_dl)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")