# -*- coding: utf-8 -*-
"""Environement setup and testing (final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAWNeY3hG5Hc_X92FHF5QGEsIihHhupK
"""

from google.colab import files
uploaded= files.upload()

!pip install torch torchvision timm numpy opencv-python scikit-learn joblib matplotlib

!unzip ship_detection_system.zip

import torch
import torch.nn as nn
import timm
import numpy as np
import cv2
import joblib
import matplotlib.pyplot as plt
from torchvision import transforms
from sklearn.neighbors import NearestNeighbors

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)

class ShipNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = timm.create_model(
            "efficientnet_b0",
            pretrained=False,
            num_classes=0
        )
        self.classifier = nn.Linear(1280, 2)

    def forward(self, x):
        feat = self.backbone(x)
        out = self.classifier(feat)
        return out, feat

def load_system():
    model = ShipNet().to(DEVICE)
    model.load_state_dict(
        torch.load("efficientnet_b0_ship.pth", map_location=DEVICE)
    )
    model.eval()

    dbscan = joblib.load("dbscan.pkl")
    nn_index = joblib.load("nn_index.pkl")
    ship_centroid = np.load("ship_centroid.npy")
    cluster_labels = np.load("cluster_labels.npy")

    return model, dbscan, nn_index, ship_centroid, cluster_labels

class GradCAM:
    def __init__(self, model):
        self.model = model
        self.grad = None
        self.act = None

        layer = model.backbone.conv_head
        layer.register_forward_hook(self._save_act)
        layer.register_backward_hook(self._save_grad)

    def _save_act(self, m, i, o):
        self.act = o

    def _save_grad(self, m, gi, go):
        self.grad = go[0]

    def generate(self, x, cls):
        self.model.zero_grad()
        logits,_ = self.model(x)
        logits[0, cls].backward()

        w = self.grad.mean(dim=(2,3), keepdim=True)
        cam = (w * self.act).sum(1)
        cam = torch.relu(cam)

        cam = cam.squeeze().detach().cpu().numpy()
        return cam / cam.max()

def run_inference(image_path,
                  conf_thresh=0.65,
                  dist_thresh=15.0):

    model, dbscan, nn_index, ship_centroid, cluster_labels = load_system()
    gradcam = GradCAM(model)

    # Load image
    img = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    if img is None:
        raise ValueError("Image not found")

    if img.ndim == 2:
        img = np.stack([img]*3, axis=-1)

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, (224,224))

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485,0.456,0.406],
            std=[0.229,0.224,0.225]
        )
    ])

    x = transform(img_resized).unsqueeze(0).to(DEVICE)

    # Forward
    with torch.no_grad():
        logits, feat = model(x)
        probs = torch.softmax(logits,1)
        conf, pred = probs.max(1)

    confidence = conf.item()
    raw_label = "Ship" if pred.item()==1 else "No-Ship"

    # Unknown detection
    feat_np = feat.detach().cpu().numpy()
    dist = np.linalg.norm(feat_np - ship_centroid)

    final_label = raw_label
    if confidence < conf_thresh or dist > dist_thresh:
        final_label = "Unknown Ship"

    # Clustering
    _, idx = nn_index.kneighbors(feat_np)
    cluster_id = int(cluster_labels[idx[0][0]])

    # Grad-CAM
    cam = gradcam.generate(x, pred.item())

    # Display
    plt.figure(figsize=(14,4))

    plt.subplot(1,3,1)
    plt.imshow(img_rgb)
    plt.title("Input Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(cam, cmap="jet")
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.text(0.05,0.8,f"Final Label: {final_label}", fontsize=12)
    plt.text(0.05,0.6,f"Confidence: {confidence:.3f}", fontsize=12)
    plt.text(0.05,0.4,f"Cluster ID: {cluster_id}", fontsize=12)
    plt.text(0.05,0.2,f"Distance: {dist:.2f}", fontsize=12)
    plt.axis("off")

    plt.show()

from google.colab import files
uploaded= files.upload()

run_inference("test.jpg")